name: Build and Release Debian Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper build-essential devscripts
    
    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc -b
    
    - name: Get version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="dev-$(date +%Y%m%d)"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ../*.deb
        body: |
          ## Installation
          
          ### Ubuntu/Debian
          Download the `.deb` file and install:
          ```bash
          sudo dpkg -i nyancat-neofetch_*.deb
          sudo apt-get install -f  # Fix any dependencies
          ```
          
          ### Usage
          ```bash
          nyanfetch
          ```
          
          Press `Ctrl+C` to exit.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload artifact
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v3
      with:
        name: debian-package
        path: ../*.deb
